module.exports = [
    {
        question: "What is DarchAI?",
        answer: "DarchAI is the world's first AI-powered debate evidence search engine. Here's how it works: <ul>"+
        "<li> You enter an argument </li>"+
        "<li> DarchAI finds articles that support your argument </li>"+
        "<li> You can then download these articles and use them </li>"+
        "</ul>"
    },
    {
        question: "Is DarchAI free?",
        answer: "DarchAI is free during our open beta"
    },
    {
        question: "Does DarchAI work for all topics?",
        answer: "<p>In general, we have found DarchAI to perform well on most topics, although it seems to struggle a bit with more complex philosophical arguments. We are always working on improving DarchAI, so if you find that DarchAI is not working well for your topic, please let us know.</p>"+
        "Please look for more specific information in our <a href='/docs'>documentation.</a>"
    },
    {
        question: "Does DarchAI have bias?",
        answer: "While we cannot claim that DarchAI does not have any biases, in general DarchAI has minimal bias. This is because DarchAI is a search engine, so it is very limited by the evidence that it finds. <p> Please read our <a href='/docs'>documentation</a> for more information.</p>"
    },
    {
        question: "Does DarchAI hallucinate evidence?",
        answer: "<p>DarchAI does not hallucinate evidence as it is a search engine. However, DarchAI may occasionaly find evidence that is not relevant to your argument. We would always recommend users to read any evidence they use from DarchAI. Please remember that DarchAI is supposed to supplement research, not replace it. </p>"+
        "<p>The exception is that the taglines generated by DarchAI may occasionally be inaccurate, espically with shorter pieces of evidence. We are always working on improving this, so please make sure to reach out with any concerns or feedback.</p>"
    }
]